# Name of the workflow
name: Python services test

# This workflow is triggered on pushes to any branch in the repo
on:
  push:
    branches:
      - '**'

# Defines two separate jobs for testing the two services
jobs:
  # First job for testing quote_gen service
  test_quote_gen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3 # Checks out repo under $GITHUB_WORKSPACE, so the job can access it

      - name: Set up Python 3.x
        uses: actions/setup-python@v3 # Sets up a Python environment
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use

      - name: Install dependencies for quote_gen
        run: |
          pip install -r quote_gen/requirements.txt

      - name: Run tests in quote_gen
        run: |
          cd quote_gen
          pytest

  # Second job for testing quote_disp service
  test_quote_disp:
    runs-on: ubuntu-latest
    needs: test_quote_gen # This job needs test_quote_gen to complete before it starts

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies for quote_disp
        run: |
          pip install -r quote_disp/requirements.txt

      - name: Run tests in quote_disp
        run: |
          cd quote_disp
          pytest